# FLight Radar24 ADB-S Antenna - Flight Tracker
- platform: rest
  name: FR24 Feeder
  resource: !secret flight_radar_monitor_url
  value_template: "{{ value_json.feed_alias }}"
  method: GET
  scan_interval: 60
  json_attributes:
    - rx_connected
    - feed_status
    - d11_map_size
    - feed_num_ac_tracked
    - build_version
    - feed_alias

- platform: template
  sensors:
    fr24_feeder_radar_code:
      friendly_name: Radar Code
      value_template: "{{ state_attr('sensor.fr24_feeder','feed_alias') }}"
    fr24_feeder_aircraft_tracked:
      friendly_name: Aircraft Tracked
      value_template: "{{ state_attr('sensor.fr24_feeder','d11_map_size') | round(0) }}"
      unit_of_measurement: "aircrafts"
    fr24_feeder_aircraft_uploaded:
      friendly_name: Aircraft Uploaded
      value_template: "{{ state_attr('sensor.fr24_feeder','feed_num_ac_tracked') | round(0) }}"
      unit_of_measurement: "aircrafts"
    fr24_feeder_version:
      friendly_name: Version
      value_template: "{{ state_attr('sensor.fr24_feeder','build_version') }}"