sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_free
      - type: ipv4_address
        arg: eth0
      - type: processor_temperature
      - type: last_boot