language: python
python:
- "3.8"
before_install:
- cp travis_secrets.yaml secrets.yaml
- touch home-assistant_v2.db
- touch home-assistant.log
- sudo apt-get install -y libudev-dev
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config