- platform: template
  sensors:
    fr24_feeder_online:
      friendly_name: FR24 Feeder Status
      value_template: '{{ is_state_attr("sensor.fr24_feeder", "rx_connected", "1") }}'
      device_class: connectivity
    fr24_feeder_link_connected:
      friendly_name: FR24 Upstream Connection Status
      value_template: '{{ is_state_attr("sensor.fr24_feeder", "feed_status", "connected") }}'
      device_class: connectivity