- platform: template
  sensors:
    is_home_empty:
        device_class: occupancy
        friendly_name: Someone Home
        icon_template: >-
          {% if is_state('binary_sensor.is_home_empty','on') %}
            mdi:home-account
          {% else %}
            mdi:home-outline
          {% endif %}
        value_template: "{{ is_state('person.emmanuel','home') or  is_state('person.iris','home') }}"