- alias: "Landscape Lighting. Turn ON Main door"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: input_number.landscape_lighting_elevation
  condition:
    - condition: state
      entity_id: 'input_boolean.landscape_lighting_main_door'
      state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.landscape_lighting_main_door
    
- alias: "Landscape Lighting. Turn OFF"
  trigger:
    platform: time
    at: input_datetime.landscape_lighting_stop_time
  action:
    service: switch.turn_off
    entity_id: switch.landscape_lighting_main_door