- alias: "Landscape Lighting. Turn ON Main door"
  trigger:
    platform: template
    value_template: >
      {{ state_attr('sun.sun','elevation')|float <= states('input_number.landscape_lighting_elevation')|float }}
  condition:
    - condition: state
      entity_id: 'input_boolean.landscape_lighting_main_door'
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.landscape_lighting_main_door
        - switch.driveway
    
- alias: "Landscape Lighting. Turn OFF"
  trigger:
    platform: time
    at: input_datetime.landscape_lighting_stop_time
  action:
    - service: switch.turn_off
      entity_id: switch.landscape_lighting_main_door
    - service: switch.turn_off
      entity_id: switch.driveway