- alias: "Landscape Lighting. Turn ON"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 3.20
  condition:
    - condition: state
      entity_id: 'input_boolean.landscape_lighting_front_yard'
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.landscape_lighting_plug
        - switch.driveway
    
- alias: "Landscape Lighting. Turn OFF"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -2
  action:
    - service: switch.turn_off
      entity_id:
        - switch.landscape_lighting_plug
        - switch.driveway