- alias: "Christmas: TURN ON Christmas Tree"
  trigger:
    platform: time
    at: '17:10:00'
  condition:
    condition: state
    entity_id: input_boolean.christmas_tree
    state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_1

- alias: "Christmas: TURN OFF Christmas Tree"
  trigger:
    platform: time
    at: '01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.christmas_tree
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_1
