#
# Monitor internet upload and downloads speed.
#

- alias: 'Slow Internet Connection Upload'
  mode: single
  trigger:
    platform: numeric_state
    entity_id: sensor.speedtest_upload
    below: 7
  action:
    service: script.admin_notifications
    data: 
      message: >
        "Speed measured : {{ states('sensor.speedtest_upload') }} {{ state_attr('sensor.speedtest_upload','unit_of_measurement') }}
         Time : {{ now() }}"
      name: 'Slow Internet Connection Upload'
      entity_id: automation.slow_internet_connection_upload

- alias: 'Normal Internet Connection Upload'
  trigger:
    platform: numeric_state
    entity_id: sensor.speedtest_upload
    above: 10
  action:
    service: notify.telegram_network_chat
    data:
      title: "[Resolution] Internet Upload Speed Restored"
      message: >
        "Speed measured : {{ states('sensor.speedtest_upload') }} {{ state_attr('sensor.speedtest_upload','unit_of_measurement') }}
         Time : {{ now() }}"

- alias: 'Slow Internet Connection Download'
  mode: single
  trigger:
    platform: numeric_state
    entity_id: sensor.speedtest_download
    below: 200
  action:
    service: script.admin_notifications
    data: 
      message: >
        "Speed measured : {{ states('sensor.speedtest_download') }} {{ state_attr('sensor.speedtest_download','unit_of_measurement') }}
         Time : {{ now() }}"
      name: 'Slow Internet Connection Download'
      entity_id: automation.slow_internet_connection_download


- alias: 'Normal Internet Connection Download'
  trigger:
    platform: numeric_state
    entity_id: sensor.speedtest_download
    above: 200
  action:
    service: notify.telegram_network_chat
    data:
      title: "[Resolution] Internet Download Speed Restored"
      message: >
        "Speed measured : {{ states('sensor.speedtest_download') }} {{ state_attr('sensor.speedtest_download','unit_of_measurement') }}
         Time : {{ now() }}"